# Exercise 5.A NumPy Fundamentals

This notebook practices creating and working with NumPy arrays,
including one dimensional arrays, two dimensional arrays,
array slicing, transposing arrays, and checking data types.

In [1]:
import numpy as np

## Array Basics

In [6]:
fruits = ["apple", "banana", "cherry", "date"]
          
print(fruits)          

['apple', 'banana', 'cherry', 'date']


In [7]:
arr_1 = np.array(fruits)

print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [8]:
print(arr_1.dtype)

<U6


The letter U means Unicode string. The number 6 means the maximum string length is 6 characters.

In [9]:
arr_2 = np.array ([
    [10, 11, 12],
    [13, 14, 15]
])

print(arr_2)

[[10 11 12]
 [13 14 15]]


In [10]:
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [11]:
print(arr_2)

[[10 11 12]
 [13 14 15]]


arr_2 itself was not permanently changed | .T only displays a transposed version.

In [12]:
arr_3 = np.array([
    [1, 3, 5],
    [2, 4, 6]
])

print(arr_3)

[[1 3 5]
 [2 4 6]]


In [13]:
arr_4 = np.array([
    arr_3[0, 2],
    arr_3[1, 1]
])

print(arr_4)

[5 4]


In [14]:
arr_5 = np.ones((2, 2, 2))

print(arr_5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


arr_5 is a three dimensional array filled with ones. Each dimension contains 2 values. 