# Exercise 1.A NumPy: Manipulating Arrays

In [1]:
import numpy as np

## Looping Through Arrays

In [5]:
arrA = np.array([[11, 12, 13],
                [14, 15, 16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [6]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [7]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


The first loop multiplies each row by 2 as a group. The second loop goes thourgh each individual value and multiplies each number by 2 seperately.

In [9]:
for x in arrA:
    for y in x:
        loop_result = y * 2
        print(loop_result)

22
24
26
28
30
32


The results contain the same values, but the first loop works with entire rows of the array while the second loop works with each individual number separetly. The first loop prints arrays, and the second loop prints one value at a time.

## Joining and Stacking Arrays

In [11]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [13]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [15]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [16]:
# This will create an error because the arrays do not have matching shapes.
stacked_array_2 = np.stack((joined_array_1, joined_array_2))
print(stacked_array_2)

ValueError: all input arrays must have the same shape

In [17]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [18]:
# This creates an error because the number of columns does not match for axis=1.
another_2 = np.concatenate((joined_array_1, arrA), axis = 1)
print(another_2)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [19]:
horizontal_stack = np.hstack((arrA, arrA))
print(horizontal_stack)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


hstack joins arrays side by side horizontally.

In [20]:
vertical_stack = np.vstack((arrA, arrA))
print(vertical_stack)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


vstack joins arrays on top of each other vertically.

In [21]:
depth_stack = np.dstack((arrA, arrA))
print(depth_stack)

[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


dstack stacks arrays by depth, creating a third dimension.

# Splitting Arrays

In [22]:
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


This splits the array into 2 smaller arrays. Each array still have 2 dimensions.

In [23]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


This splits the array into 3 arrays. Each array is still 2 dimensional, but the rows are unevenl divided.

# Searching and Replacing Array Values

In [24]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


# Sorting and Filtering Arrays

In [25]:
arrB = np.array([[7, 6],
                 [13, 5],
                 [7, 3]])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [28]:
print(arrB)

z = arrB < 7
arrC = arrB[z]

print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [29]:
z = arrB >= 7
arrD = arrB[z]

print(arrD)

[ 7 13  7]
