# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [2]:
r_1 = np.random.randint(1, 20, size=2)
print(r_1)

[8 9]


In [3]:
r_2 = np.random.randint(1, 20, size=(1, 2))
print(r_2)

[[18 13]]


In [4]:
r_3 = np.random.rand(2, 1)
print(r_3)

[[0.56535868]
 [0.48377358]]


In [5]:
r_4 = np.random.randint(20, 100, size=(4, 5))
print(r_4)

[[52 24 27 90 94]
 [81 29 95 96 33]
 [71 36 50 83 65]
 [74 58 53 75 25]]


In [6]:
r_5 = np.random.rand(4, 5)
print(r_5)

[[0.88130351 0.85059082 0.77407552 0.77050032 0.68925285]
 [0.09122548 0.65454065 0.06261492 0.74832793 0.12102891]
 [0.97679243 0.69967897 0.55255326 0.13820451 0.85934205]
 [0.1219608  0.8801883  0.81679191 0.53870125 0.49766901]]


## Generating Random Choices from an Array

In [8]:
students = np.array([
    "Alex", "Jordan", "Taylor", "Morgan",
    "Casey", "Riley", "Jamie", "Avery",
    "Parker", "Cameron", "Skyler", "Quinn"
])
print(students)

['Alex' 'Jordan' 'Taylor' 'Morgan' 'Casey' 'Riley' 'Jamie' 'Avery'
 'Parker' 'Cameron' 'Skyler' 'Quinn']


In [9]:
call_on = np.random.choice(students)
print(call_on)

Taylor


In [10]:
breakout_groups = np.random.choice(students, size=(3, 4))
print(breakout_groups)
# This could work for breakout groups, but some students may repeat while others may not be selected.

[['Casey' 'Cameron' 'Morgan' 'Riley']
 ['Jamie' 'Cameron' 'Riley' 'Casey']
 ['Quinn' 'Riley' 'Taylor' 'Taylor']]


In [14]:
call_on_weighted = np.random.choice(
    students,
    size=5,
    p=[0.30, 0.10, 0.10, 0.05, 0.05, 0.10,
       0.00, 0.05, 0.05, 0.05, 0.10, 0.05]
)
print(call_on_weighted)
# Alex has a 30% chance of being selected.
# Jamie has a 0% chance of being selected.
# The remaining students have smaller probabilities distributed across the array.

['Taylor' 'Avery' 'Cameron' 'Cameron' 'Avery']


## Generating a Normal Distribution

In [16]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))
print(bell_curve)

[[ 9.51606033 11.23794575 11.75965867 10.86522245  5.88465538]
 [10.79538425  1.76008107 15.12578359  1.37866809 12.0705393 ]
 [ 1.94436044  8.0405549   5.88844082 11.57072213 16.44084371]
 [ 6.34173353  7.92444842  5.94764412 13.50910102  6.75241359]]
