# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np

## Sample Arrays

In [2]:
r_1 = np.random.randint(1, 20, size=2)
print(r_1)

[3 2]


In [3]:
r_2 = np.random.randint(1, 20, size=(1, 2))
print(r_2)

[[16 12]]


In [4]:
r_3 = np.random.rand(2, 1)
print(r_3)

[[0.86583641]
 [0.7460223 ]]


In [5]:
r_4 = np.random.randint(20, 100, size=(4, 5))
print(r_4)

[[24 71 36 83 66]
 [39 89 90 82 63]
 [96 73 84 93 43]
 [42 51 34 98 78]]


In [6]:
r_5 = np.random.rand(4, 5)
print(r_5)

[[0.65166629 0.95251954 0.93065957 0.44515768 0.06489899]
 [0.10393196 0.46513072 0.66102873 0.9487678  0.02277681]
 [0.20379756 0.35677375 0.23644076 0.37891571 0.76769618]
 [0.81503392 0.36503974 0.21380354 0.15262287 0.8608489 ]]


## Permutations

In [7]:
print(r_4)

[[24 71 36 83 66]
 [39 89 90 82 63]
 [96 73 84 93 43]
 [42 51 34 98 78]]


In [8]:
np.random.shuffle(r_4)
print(r_4)

[[39 89 90 82 63]
 [24 71 36 83 66]
 [42 51 34 98 78]
 [96 73 84 93 43]]


This rows of the array were shuffled into a different order.

In [10]:
new_shuffle = np.random.permutation(r_4)
print(new_shuffle)

print(r_4)

[[24 71 36 83 66]
 [39 89 90 82 63]
 [96 73 84 93 43]
 [42 51 34 98 78]]
[[39 89 90 82 63]
 [24 71 36 83 66]
 [42 51 34 98 78]
 [96 73 84 93 43]]


Shuffle changes the original array directly. Permulation creates a shuffled copy while keeping the original array unchanged.

# Mathematical Operations

In [11]:
print(r_1)
print(r_1.shape)

print(r_2)
print(r_2.shape)

result_1 = np.add(r_1, r_2)
print(result_1)
print(result_1.shape)

[3 2]
(2,)
[[16 12]]
(1, 2)
[[19 14]]
(1, 2)


In [12]:
print(r_1)
print(r_1.shape)

print(r_3)
print(r_3.shape)

result_2 = np.add(r_1, r_3)
print(result_2)
print(result_2.shape)

[3 2]
(2,)
[[0.86583641]
 [0.7460223 ]]
(2, 1)
[[3.86583641 2.86583641]
 [3.7460223  2.7460223 ]]
(2, 2)


In [13]:
print(r_2)
print(r_2.shape)

print(r_4)
print(r_4.shape)

result_3 = np.add(r_2, r_4)
print(result_3)
print(result_3.shape)

[[16 12]]
(1, 2)
[[39 89 90 82 63]
 [24 71 36 83 66]
 [42 51 34 98 78]
 [96 73 84 93 43]]
(4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

This will create an error because the array shapes are incompatible.

In [17]:
np.add(r_1, r_4)

ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

This will also create an error because the shapes do not match correctly.


In [18]:
np.add(r_2, r_3)

array([[16.86583641, 12.86583641],
       [16.7460223 , 12.7460223 ]])

In [19]:
print(np.add(np.array([1]), r_4))

[[40 90 91 83 64]
 [25 72 37 84 67]
 [43 52 35 99 79]
 [97 74 85 94 44]]


In [20]:
print(np.add(np.array([[1]]), r_4))

[[40 90 91 83 64]
 [25 72 37 84 67]
 [43 52 35 99 79]
 [97 74 85 94 44]]


In [21]:
print(np.add(np.array([1,1,1,1,1]), r_4))

[[40 90 91 83 64]
 [25 72 37 84 67]
 [43 52 35 99 79]
 [97 74 85 94 44]]


In [22]:
np.add(np.array([[1],[1]]), r_4)

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

This produces an error because the shapes cannot broadcast together.

Broadcasting works by matching array shapes together. Values are added element by element when the dimensions are compatible. The resulting array shape is based on the larger compatible dimensions.

# Rounding

In [23]:
print(r_3)

[[0.86583641]
 [0.7460223 ]]


In [24]:
print(np.trunc(r_3))

[[0.]
 [0.]]


In [25]:
print(np.fix(r_3))

[[0.]
 [0.]]


In [26]:
print(np.floor(r_3))

[[0.]
 [0.]]


In [27]:
print(np.ceil(r_3))

[[1.]
 [1.]]


In [28]:
print(np.round(r_3, 2))

[[0.87]
 [0.75]]


# Cumulative Operations

In [29]:
print(r_4)

[[39 89 90 82 63]
 [24 71 36 83 66]
 [42 51 34 98 78]
 [96 73 84 93 43]]


In [30]:
print(np.sum(r_4))

1335


In [31]:
print(np.sum(r_4, axis=0))

[201 284 244 356 250]


In [32]:
print(np.sum(r_4, axis=1))

[363 280 303 389]


In [33]:
print(np.cumsum(r_4))

[  39  128  218  300  363  387  458  494  577  643  685  736  770  868
  946 1042 1115 1199 1292 1335]


In [34]:
print(np.cumsum(r_4, axis=0))

[[ 39  89  90  82  63]
 [ 63 160 126 165 129]
 [105 211 160 263 207]
 [201 284 244 356 250]]


# Grocery Problem

In [35]:
bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])

print(bag1)
print(bag2)

[2 3 4 0]
[4 0 1 2]


In [36]:
total_bag1 = np.sum(bag1)
total_bag2 = np.sum(bag2)

print(f"The first bag contains {total_bag1} items, and the second bag contains {total_bag2} items.")

The first bag contains 9 items, and the second bag contains 7 items.


In [38]:
totals = np.add(bag1, bag2)
print(f"There are {totals[0]} vegetables, {totals[1]} fruits, {totals[2]} boxes of snacks, and {totals[3]} beverages in the two grocery bags.")

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


# Teamwork

In [39]:
ali = np.array([5, 4, 6, 4, 2])
print(ali)

[5 4 6 4 2]


In [40]:
ben = np.array([0, 5, 5, 3, 4])
print(ben)

[0 5 5 3 4]


In [41]:
carla = np.array([3, 6, 0, 3, 4])
print(carla)

[3 6 0 3 4]


In [42]:
all_knocks = np.array([ali, ben, carla])
print(all_knocks)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [43]:
person_totals = np.sum(all_knocks, axis=1)
group_total = np.sum(all_knocks)

print(person_totals)
print(group_total)

[21 17 16]
54


In [44]:
daily_totals = np.sum(all_knocks, axis=0)

rolling_votes = np.cumsum(daily_totals) * 0.5

print(rolling_votes)

[ 4.  11.5 17.  22.  27. ]
